### PR TITLE
Add composer.install Makefile target

### PR DESCRIPTION
**Pull request by rparpa**
Also add .PHONY configuration

### CODE REVIEW

**Comment by louiscelier** [comment]
Beware, you add a docker run before build in the CI. The make setup should maybe launch docker-compose up -d !

**Comment by rparpa** [comment]
@louiscelier run !== exec

run : run a command on a docker-compose specified service
exec : run a command on a started container

**Comment by rparpa** [comment]
Fixed conflicts

**Comment by rparpa** [comment]
Fixed conflicts

**Comment by rparpa** [comment]
Fixed conflicts

**Pull request closed without merging**
